#----------------------------------------------------------------------
#           GLOBAL MAKEFILE
#----------------------------------------------------------------------

# Local settings (optional). See Makefile.local.example for an example.
# WARNING: do not commit to a repository!
-include eliom_Makefiles/Makefile.local

# Eliom settings. Contains all variables.
include eliom_Makefiles/Makefile.options

# Eliom default makefile
# Makefile.PROJECT_NAME is also included in this makefile
include eliom_Makefiles/Makefile.app